### ISSUE TITLE
shouldPublish not working

### ISSUE THREAD

**Issue by nanitook** [Ulferno/upload-to-roblox#3]
After adding `shouldPublish: false` to the .yml file, the request is still made with the "Published" parameter.

Just in case, I've already looked and there's no typos from my side.

**Comment by MacaylaMarvelous81** [comment]
Same thing happens to me, it worked before I upgraded to 1.0.3 (I used to use 1.0.1). I think this is caused by GitHub Actions toolkit updating, and I will try to PR a fix soon.
